# Generated by Django 4.0.2 on 2022-02-28 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.CharField(max_length=30)),
                ('badge_description', models.TextField(default='')),
                ('badge_image', models.ImageField(default='badge_images/badge_default.jpg', upload_to='badge_images')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.CharField(max_length=100)),
                ('student_badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landingpage.badge')),
            ],
        ),
    ]
